<template>
  <div class="loadingio-spinner-dual-ball-bjn6y1o67dr">
    <div class="ldio-voyt9tnbjl">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'Loading'
}
</script>

<style>

@keyframes ldio-voyt9tnbjl-o {
  0% {
    opacity: 1;
    transform: translate(0 0)
  }

  49.99% {
    opacity: 1;
    transform: translate(80px, 0)
  }

  50% {
    opacity: 0;
    transform: translate(80px, 0)
  }

  100% {
    opacity: 0;
    transform: translate(0, 0)
  }
}

@keyframes ldio-voyt9tnbjl {
  0% {
    transform: translate(0, 0)
  }

  50% {
    transform: translate(80px, 0)
  }

  100% {
    transform: translate(0, 0)
  }
}

.ldio-voyt9tnbjl div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  top: 50%;
  left: 0;
}

.ldio-voyt9tnbjl div:nth-child(1) {
  background: #eaeaea;
  animation: ldio-voyt9tnbjl 1s linear infinite;
  animation-delay: -0.5s;
}

.ldio-voyt9tnbjl div:nth-child(2) {
  background: #0fb1bf;
  animation: ldio-voyt9tnbjl 1s linear infinite;
  animation-delay: 0s;
}

.ldio-voyt9tnbjl div:nth-child(3) {
  background: #eaeaea;
  animation: ldio-voyt9tnbjl-o 1s linear infinite;
  animation-delay: -0.5s;
}

.loadingio-spinner-dual-ball-bjn6y1o67dr {
  width: 120px;
  height: 120px;
  display: block;
  overflow: hidden;
  background: none;
}

.ldio-voyt9tnbjl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
  /* see note above */
}

.ldio-voyt9tnbjl div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>